name: anti_proxy_enrollment_page
description: "An app for CV-based fast and accurate automatic attendance marking"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Packages for the stable app
  camera: ^0.10.0
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  uuid: ^4.4.0
  path_provider: ^2.1.3
  path: ^1.9.0
  csv: ^6.0.0
  excel: ^4.0.3
  intl: ^0.19.0
  http: ^1.2.1
  flutter_card_swiper: ^7.0.1
  appinio_swiper: ^2.1.1
  # Added for secure JWT storage
  flutter_secure_storage: ^9.0.0
  # Added for image caching
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  # Added for PDF generation
  pdf: ^3.10.8
  printing: ^5.12.0
  # Added for calling and emailing
  url_launcher: ^6.3.0
  google_fonts: ^6.1.0
  # Bluetooth classic scanning for ESP32
  flutter_bluetooth_serial_plus: ^0.5.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dtu_logo.png
    - assets/images/